server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-catalog

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - java.io.IDException
          - java.net.SocketTimeoutException
    instances:
      retryConfig:
        baseConfig: default
        maxRetryAttempts: 5
        waitDuration: 2s
        retryExceptions:
          - java.net.ConnectException
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 30s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
    instances:
      clientConfig:
        baseConfig: default
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        waitDurationInOpenState: 1m
        failureRateThreshold: 20
