server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-serie
  zipkin:
    baseUrl: http://localhost:9412/
  data:
    mongodb:
      username: usr-serie-mongo
      password: pwd-serie-mongo
      database: serie-dev-mongo
      port: 27018
      host: localhost

info:
  aplication:
    name: api-serie

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

