server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-catalog
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5673
  zipkin:
    baseUrl: http://localhost:9411/
  data:
    mongodb:
      database: test
      port: 27018
      host: localhost
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      ClientCatalog:
        registerHealthIndicator: 'true'
        allowHealthIndicatorToFail: 'false'
        slidingWindowType: COUNT_BASED
        slidingWindowSize: '10'
        failureRateThreshold: '40'
        permittedNumberOfCallsInHalfOpenState: '3'
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        waitDurationInOpenState: '15000'
  retry:
    instances:
      retryCatalog:
        maxAttempts: '3'
        waitDuration: '1000'

